version: '3'

services:
  db:
    image: postgres:15.1-alpine
    container_name: wallet_service_db
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=wallet_service
    ports:
      - "5435:5432"